membersrvc:
        image: ibmblockchain/fabric-membersrvc
        ports:
                - "7054:7054"
        environment:
                - MEMBERSRVC_CA_ACA_ENABLED=true
        command: membersrvc
vp:
        image: ibmblockchain/fabric-peer
        environment:
                - CORE_PEER_ADDRESSAUTODETECT=true
                - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
                - CORE_LOGGING_LEVEL=INFO
                - CORE_LOGGING_CHAINCODE=DEBUG
                - CORE_SECURITY_ENABLED=true
                - CORE_SECURITY_PRIVACY=true
                - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
                - CORE_PBFT_GENERAL_MODE=batch
        volumes:
                - /var/run/docker.sock:/var/run/docker.sock

vp0:
        extends:
                service: vp
        ports:
                - "7050:7050"
                - "7051:7051"
                - "7053:7053"
        environment:
                - CORE_PEER_ID=vp0
                - CORE_SECURITY_ENROLLID=test_vp0
                - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
                - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
                - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
                - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
        links:
                - membersrvc
        command: sh -c "sleep 5; peer node start"
vp1:
        extends:
                service: vp
        ports:
                - "7150:7050"
                - "7151:7051"
                - "7153:7053"
        environment:
                - CORE_PEER_ID=vp1
                - CORE_SECURITY_ENROLLID=test_vp1
                - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
                - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
                - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
                - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
                - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
        links:
                - membersrvc
                - vp0
        command: sh -c "sleep 8; peer node start"
vp2:
        extends:
                service: vp
        ports:
                - "7250:7050"
                - "7251:7051"
                - "7253:7053"
        environment:
                - CORE_PEER_ID=vp2
                - CORE_SECURITY_ENROLLID=test_vp2
                - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
                - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
                - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
                - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
                - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
        links:
                - membersrvc
                - vp0
        command: sh -c "sleep 11; peer node start"
vp3:
        extends:
                service: vp
        ports:
                - "7350:7050"
                - "7351:7051"
                - "7353:7053"
        environment:
                - CORE_PEER_ID=vp3
                - CORE_SECURITY_ENROLLID=test_vp3
                - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
                - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
                - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
                - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
                - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
        links:
                - membersrvc
                - vp0
        command: sh -c "sleep 14; peer node start"
